[package]
name = "error_trait"
version = "0.1.0"
edition = "2021"

[dependencies]
helpers = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, default-features = true, features = ["fmt"] }
